# Atom-AppVeyor-CI-Template

# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that run after cloning repository
install:
  - cinst atom
  - cd %APPVEYOR_BUILD_FOLDER%
  - apm install

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - apm test

# to disable automatic tests
test: off

# to disable deployment
deploy: off
